sources:
    base_socios:
        type: file
        sheet: Consolidado
        skiprows: 1
        encoding: latin-1
        columns: 
            - column: cod_cliente
              pos: 1
            - column: cod_loc
              pos: 2
            - column: cod_agente
              pos: 3
            - column: atencion
              pos: 4
        converters:
            cod_cliente: number
            cod_loc: number
            cod_agente: number
    base_coordenadas:
        type: file
        sheet: Base
        skiprows: 1
        encoding: latin-1
        columns: 
            - column: cod_cliente
              pos: 1
            - column: latitud
              pos: 2
            - column: longitud
              pos: 3
            - column: cod_agente
              pos: 4
            - column: cod_ecom
              pos: 5
        converters:
            cod_cliente: number
            cod_agente: number
            cod_ecom: number
    base_universo_directa:
        type: file
        sheet: Maestra
        skiprows: 1
        encoding: latin-1
        columns: 
            - column: cod_cliente
              pos: 2
            - column: nom_cliente
              pos: 5
            - column: direccion
              pos: 10
            - column: cod_vendedor
              pos: 24
            - column: vendedor
              pos: 25
            - column: subcanal
              pos: 49
            - column: cod_jefe
              pos: 57
            - column: jefe
              pos: 58
        converters:
            cod_cliente: number
            cod_vendedor: number
            cod_jefe: number
    base_universo_indirecta:
          type: file
          sheet: BD
          skiprows: 1
          encoding: latin-1
          columns:
              - column: cod_agente
                pos: 2 
              - column: agente
                pos: 3 
              - column: cod_cliente
                pos: 7 
              - column: direccion
                pos: 14
              - column: subcanal
                pos: 28
          converters:
              cod_agente: number
              cod_cliente: number
              subcanal: number
    base_consulta_directa:
          type: folder
          sheet: 0
          skiprows: 1
          encoding: latin-1
          columns: 
              - - column: cod_cliente
                  pos: 1
                - column: mes
                  pos: 2
                - column: marca
                  pos: 3
                - column: venta_pesos
                  pos: 4
                - column: venta_kilos
                  pos: 5
          converters:
              cod_cliente: number
              venta_pesos: number
              venta_kilos: number
    base_consulta_indirecta:
        type: folder
        sheet: 0
        skiprows: 3
        encoding: latin-1
        columns: 
            - - column: cod_agente
                pos: 1
              - column: cod_ecom
                pos: 2
              - column: marca
                pos: 3
              - column: venta_pesos
                pos: '4-15'
              - column: venta_kilos
                pos: '16-27'
            - - column: cod_agente
                pos: 1
              - column: cod_ecom
                pos: 2
              - column: marca
                pos: 3
              - column: venta_pesos
                pos: '4-7'
              - column: venta_kilos
                pos: '8-11'
        converters:
              cod_agente: number
              cod_ecom: number
              venta_pesos: number
              venta_kilos: number
order_base:
  - base_universo_directa
  - base_universo_indirecta
  - base_socios
  - base_coordenadas
  - base_consulta_directa
  - base_consulta_indirecta
final_base:
    - cod_cliente
    - nom_cliente
    - atencion
    - direccion
    - subcanal
    - cod_vendedor
    - vendedor
    - cod_vendedor_2
    - vendedor_2
    - cod_jefe
    - jefe
    - socio
    - latitud
    - longitud
    - ventas_ant_kilos
    - ventas_act_kilos
    - ventas_ant_kilos_marca_1
    - ventas_act_kilos_marca_1
    - ventas_ant_kilos_marca_2
    - ventas_act_kilos_marca_2
    - ventas_ant_kilos_marca_3
    - ventas_act_kilos_marca_3
    - ventas_ant_kilos_marca_4
    - ventas_act_kilos_marca_4
    - status_marca_1
    - status_marca_2
    - status_marca_3
    - status_marca_4
    - ventas_ant_pesos
    - ventas_act_pesos
    - ventas_ant_pesos_marca_1
    - ventas_act_pesos_marca_1
    - ventas_ant_pesos_marca_2
    - ventas_act_pesos_marca_2
    - ventas_ant_pesos_marca_3
    - ventas_act_pesos_marca_3
    - ventas_ant_pesos_marca_4
    - ventas_act_pesos_marca_4
